CREATE TYPE disaster_type AS ENUM (
    'Natural',
    'Man-made or Hybrid',
    'Bonus'
);

CREATE TABLE IF NOT EXISTS acclimate_disaster (
    disaster_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    disaster_name TEXT NOT NULL,
    disaster_description VARCHAR NOT NUll,
    disaster_image VARCHAR NOT NULL,
    disaster_type disaster_type NOT NULL
);