CREATE TYPE disaster_plan_step_stage AS ENUM (
    'Readiness',
    'Response',
    'Recovery'
);

CREATE TYPE disaster_plan_step_itemable_type AS ENUM (
    'Task',
    'Shopping Item'
);

-- Change the name to disaster_plan_step_stage?
CREATE TABLE IF NOT EXISTS acclimate_disaster_plan_step (
    disaster_plan_step_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    disaster_plan_step TEXT NOT NULL,
    disaster_plan_step_stage disaster_plan_step_stage NOT NULL,
    disaster_plan_step_itemable_type disaster_plan_step_itemable_type,
    disaster_plan_step_itemable_shorthand TEXT,
    disaster_program_id INTEGER REFERENCES acclimate_disaster_program(disaster_program_id)
);