CREATE TYPE disaster_plan_stage AS ENUM (
    'Readiness',
    'Response',
    'Recovery'
);

-- Change the name to disaster_plan_step_stage?
CREATE TABLE IF NOT EXISTS acclimate_disaster_plan_step (
    disaster_plan_step_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    disaster_plan_stage disaster_plan_stage NOT NULL,
    disaster_id INTEGER REFERENCES acclimate_disaster(disaster_id)
);