CREATE TABLE IF NOT EXISTS acclimate_user_task (
    user_task_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_task VARCHAR NOT NULL,
    user_id INTEGER REFERENCES acclimate_user(user_id)
);