CREATE TABLE IF NOT EXISTS acclimate_user_task_item (
    user_task_item_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_task_item VARCHAR NOT NULL,
    user_id INTEGER REFERENCES acclimate_user(user_id)
);