CREATE TABLE IF NOT EXISTS acclimate_user_shopping_item (
    user_shopping_item_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_shopping_item VARCHAR NOT NULL,
    user_id INTEGER REFERENCES acclimate_user(user_id)
);